version: "3.1"
#TODO: db-migrate up ausführen & testdaten dabei nicht ausführen
services:
  digitalisierungatschool:
    image: digitalisierungatschool/prod
    ports:
      - "6000:5000"
    volumes:
      - /digitalisierung-at-school-db-prod:/usr/share/html/db
