version: "3.1"
services:
  digitalisierungatschool:
    image: digitalisierungatschool/prod
    ports:
      - "127.0.0.1:6000:5000" # docker überschreibt die iptables der firewall. Ohne 127.0.0.1 wäre der externe Port von außerhalb erreichbar, selbst wenn die firewall den Zugriff verbietet.
    volumes:
      - ~/digitalisierung-at-school-data-prod:/usr/share/html/data
    command: [ sh, -c, "cd build/; rm migrations/*-testdaten.js; node_modules/db-migrate/bin/db-migrate up; NODE_ENV=production node src/index.js" ]
