version: '3.1'

services:
  digitalisierungatschool:
    image: digitalisierungatschool/test
    ports:
      - "5000:5000"
    volumes:
      - ~/digitalisierung-at-school-data-prod:/usr/share/html/data
