version: "3.1"
services:
  digitalisierungatschool:
    image: digitalisierungatschool/prod
    ports:
      - "6000:5000"
    volumes:
      - ~/digitalisierung-at-school-data-prod:/usr/share/html/data
    command: [ sh, -c, "cd build/; rm migrations/*-testdaten.js; node_modules/db-migrate/bin/db-migrate up; node src/index.js" ]
