version: '3.1'
#TODO: db-migrate up ausführen
services:
  digitalisierungatschool:
    image: digitalisierungatschool/test
    ports:
      - "5000:5000"
    volumes:
      - /digitalisierung-at-school-db-test:/usr/share/html/db
