version: '3.1'
services:
  digitalisierungatschool:
    image: digitalisierungatschool/test
    ports:
      - "5000:5000"
    volumes:
      - ~/digitalisierung-at-school-data-test:/usr/share/html/data
    command: [sh, -c, "cd build/; node_modules/db-migrate/bin/db-migrate up; node src/index.js"]
