@startwbs
* Digitalisierung At School
** Projektinhaber S. Vorwerk
** Projektgruppenleiter F.Lemnitzer
*** Backendleiter B.Zenz
**** Testingleiter F. Jacob
***** J. Mitzscherling
***** V. Broy
**** E. Krumbiegel
**** W. Güntzschel
**** F. Lemnitzer
***< Frontendleiter M.Schumann
**** R. Höntsch
**** J. Köhler
**** W. Kaden
**** B. Kruse
**** J. Hübner
@endwbs
