
name: Automated Testing

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install frontend
        run: npm install --prefix frontend

      - name: npm test --passWithNoTests frontend
        run: npm test --prefix frontend

      - name: npm install backend
        run: npm install --prefix backend

      - name: npm test backend
        run: npm test --prefix backend
